server.port=8080

spring.datasource.url=${jdbc:postgresql://dpg-d6l673ruibrs739nfn5g-a/csedatabase_cyx3}
spring.datasource.username=${csedatabase_cyx3_user}
spring.datasource.password=${sDqRyq8EC0rNMdrZ78giqccUHocvmQYV}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.cors.allowed-origins=http://localhost:3000,http://localhost:3001,https://your-frontend.vercel.app